version: '3.1'

services:

  postgres:
    image: postgres:latest
    restart: always
    container_name: dinamobet_custom
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - "5434:5432"